/*
 * Minesweeper API
 * A simple Minesweeper API for Deviget code challengue
 *
 * OpenAPI spec version: v1
 * Contact: juarezjaramillo@deviget.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Board', 'model/Cell', 'model/CellRef', 'model/NewBoard', 'api/BoardsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Board'), require('./model/Cell'), require('./model/CellRef'), require('./model/NewBoard'), require('./api/BoardsApi'));
  }
}(function(ApiClient, Board, Cell, CellRef, NewBoard, BoardsApi) {
  'use strict';

  /**
   * A_simple_Minesweeper_API_for_Deviget_code_challengue.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var MinesweeperApi = require('index'); // See note below*.
   * var xxxSvc = new MinesweeperApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new MinesweeperApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new MinesweeperApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new MinesweeperApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version v1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Board model constructor.
     * @property {module:model/Board}
     */
    Board: Board,
    /**
     * The Cell model constructor.
     * @property {module:model/Cell}
     */
    Cell: Cell,
    /**
     * The CellRef model constructor.
     * @property {module:model/CellRef}
     */
    CellRef: CellRef,
    /**
     * The NewBoard model constructor.
     * @property {module:model/NewBoard}
     */
    NewBoard: NewBoard,
    /**
     * The BoardsApi service constructor.
     * @property {module:api/BoardsApi}
     */
    BoardsApi: BoardsApi
  };

  return exports;
}));
