# Generated by Django 3.0.6 on 2020-05-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rows', models.IntegerField(default=8, help_text='The number of rows in the board')),
                ('num_columns', models.IntegerField(default=8, help_text='The number of columns in the board')),
                ('num_mines', models.IntegerField(default=8, help_text='The number of mines in the board')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date the board was created')),
                ('last_started', models.DateTimeField(auto_now_add=True, help_text='The date the board was last started or resumed')),
                ('elapsed', models.IntegerField(default=0, help_text='The time the board has been active for playing')),
                ('status', models.IntegerField(choices=[(1, 'Started'), (2, 'Paused'), (3, 'Finished')], default=1, help_text='The status of the board. Started, Paused or Finished')),
                ('result', models.IntegerField(blank=True, choices=[(1, 'Win'), (2, 'Lose'), (3, 'Timeout')], help_text='The result of the board. Win, Lose, Timeout', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine', models.BooleanField(default=False, help_text='Indicates if the cell contains a mine')),
                ('revealed', models.BooleanField(default=False, help_text='Indicates if the cell has been revealed')),
                ('value', models.IntegerField(blank=True, default=None, help_text='The number of adjacent cells that contain a mine', null=True)),
                ('row', models.IntegerField(default=0, help_text='The row for the cell inside the board')),
                ('column', models.IntegerField(default=0, help_text='The column for the cell inside the board')),
                ('board', models.ForeignKey(help_text='The board this cell belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='challenge.Board')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
